### PR TITLE
fix: file not found in new installation

### PR DESCRIPTION
**Pull request by nick-nds**
In new installation the pathprefix is not found and no attempt to create the directory was made by the program

### CODE REVIEW

**Comment by MASTERAMARJEET** [comment]
This feature was intentionally not included. In case the user does a typo while writing the path (which I personally do 😅), it will create a new directory with that wrong path.

**Comment by nick-nds** [comment]
> This feature was intentionally not included. In case the user does a typo while writing the path (which I personally do sweat_smile), it will create a new directory with that wrong path.

In that case, the error message should be more explicit and it should be mentioned in documentation to create an empty directory at the location specified in welearnrc.

**Comment by ParthBibekar** [comment]
Noted. Edited the error message to mention the same.

**Comment by MASTERAMARJEET** [comment]
Perhaps we can give a prompt (y/n) to the user asking if they want to create the directory.

**Pull request closed without merging**
